name: Deploy to Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 18.221.180.17
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/NasServices
          git pull origin main
          npm install --force
          npm run build
          pm2 restart 0